#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glew
Version  : 2.1.0
Release  : 25
URL      : https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0.tgz
Source0  : https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0.tgz
Summary  : The OpenGL Extension Wrangler library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: glew-lib = %{version}-%{release}
Requires: glew-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(x11)
Patch1: defaults.patch

%description
# GLEW - The OpenGL Extension Wrangler Library
![](http://glew.sourceforge.net/glew.png)

%package dev
Summary: dev components for the glew package.
Group: Development
Requires: glew-lib = %{version}-%{release}
Provides: glew-devel = %{version}-%{release}
Requires: glew = %{version}-%{release}

%description dev
dev components for the glew package.


%package lib
Summary: lib components for the glew package.
Group: Libraries
Requires: glew-license = %{version}-%{release}

%description lib
lib components for the glew package.


%package license
Summary: license components for the glew package.
Group: Default

%description license
license components for the glew package.


%prep
%setup -q -n glew-2.1.0
cd %{_builddir}/glew-2.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579725780
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
pushd ./
make  %{?_smp_mflags}  DEFAULTFLAGS="$CFLAGS" STRIP=
popd


%install
export SOURCE_DATE_EPOCH=1579725780
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glew
cp %{_builddir}/glew-2.1.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/glew/0ca22faedb8ee495473a82c4d91452493b22ac9f
cp %{_builddir}/glew-2.1.0/doc/gpl.txt %{buildroot}/usr/share/package-licenses/glew/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
pushd ./
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GL/glew.h
/usr/include/GL/glxew.h
/usr/include/GL/wglew.h
/usr/lib64/libGLEW.so
/usr/lib64/pkgconfig/glew.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libGLEW.so.2.1
/usr/lib64/libGLEW.so.2.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glew/0ca22faedb8ee495473a82c4d91452493b22ac9f
/usr/share/package-licenses/glew/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
