#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glew
Version  : 1.13.0
Release  : 4
URL      : http://downloads.sourceforge.net/project/glew/glew/1.13.0/glew-1.13.0.tgz
Source0  : http://downloads.sourceforge.net/project/glew/glew/1.13.0/glew-1.13.0.tgz
Summary  : The OpenGL Extension Wrangler library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: glew-lib
BuildRequires : cmake
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(x11)

%description
GLEW - The OpenGL Extension Wrangler Library
http://glew.sourceforge.net/
https://github.com/nigels-com/glew

%package dev
Summary: dev components for the glew package.
Group: Development
Requires: glew-lib
Provides: glew-devel

%description dev
dev components for the glew package.


%package lib
Summary: lib components for the glew package.
Group: Libraries

%description lib
lib components for the glew package.


%prep
cd ..
%setup -q -n glew-1.13.0

%build
pushd ./
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd ./
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GL/glew.h
/usr/include/GL/glxew.h
/usr/include/GL/wglew.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
